# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "country", # <clean.contact_survey>
  "..age.unit", # <clean.contact_survey>
  "..high", # <clean.contact_survey>
  "..low", # <clean.contact_survey>
  "cnt_age", # <contact_matrix>
  "age.group", # <contact_matrix>
  "part_id", # <contact_matrix>
  "lower.age.limit", # <contact_matrix>
  "population", # <contact_matrix>
  "proportion", # <contact_matrix>
  "participants", # <contact_matrix>
  "file_name", # <download_survey>
  "common_doi", # <.list_surveys>
  "doi.nb", # <.list_surveys>
  "identifier.1", # <.list_surveys>
  "title", # <.list_surveys>
  "creator", # <.list_surveys>
  "identifier.2", # <.list_surveys>
  "..main_id", # <load_survey>
  "..merge_id", # <load_survey>
  "..original.lower.age.limit", # <pop_age>
  "..segment", # <pop_age>
  "..upper.age.limit", # <pop_age>
  "population", # <pop_age>
  "sex", # <wpp_age>
  "country", # <wpp_age>
  "name", # <wpp_age>
  "country_code", # <wpp_age>
  "lower.age.limit", # <wpp_age>
  "age", # <wpp_age>
  "female", # <wpp_age>
  "male", # <wpp_age>
  NULL
))
