# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ":=", # <clean.survey>
  "..age.unit", # <clean.survey>
  "..high", # <clean.survey>
  "..low", # <clean.survey>
  ":=", # <contact_matrix>
  ".SD", # <contact_matrix>
  ".N", # <contact_matrix>
  "lower.age.limit", # <contact_matrix>
  "age.group", # <contact_matrix>
  "year", # <contact_matrix>
  "population", # <contact_matrix>
  "upper.age.limit", # <contact_matrix>
  "weight", # <contact_matrix>
  "sum_weight", # <contact_matrix>
  "dayofweek", # <contact_matrix>
  "is.weekday", # <contact_matrix>
  "age.count", # <contact_matrix>
  "age.proportion", # <contact_matrix>
  "population.proportion", # <contact_matrix>
  "population.count", # <contact_matrix>
  "weight.age", # <contact_matrix>
  "contact.age.group", # <contact_matrix>
  "id", # <contact_matrix>
  "sampled.weight", # <contact_matrix>
  "bootstrap.weight", # <contact_matrix>
  "proportion", # <contact_matrix>
  "participants", # <contact_matrix>
  "encodingFormat", # <download_survey>
  ":=", # <download_survey>
  "file_name", # <download_survey>
  "contentUrl", # <download_survey>
  ":=", # <list_surveys>
  "doi", # <list_surveys>
  "redirect", # <list_surveys>
  "identifier.3", # <list_surveys>
  "title", # <list_surveys>
  "creator", # <list_surveys>
  ":=", # <pop_age>
  "..original.lower.age.limit", # <pop_age>
  "..segment", # <pop_age>
  "..upper.age.limit", # <pop_age>
  "population", # <pop_age>
  ":=", # <wpp_age>
  "sex", # <wpp_age>
  "country", # <wpp_age>
  "name", # <wpp_age>
  "country_code", # <wpp_age>
  "year", # <wpp_age>
  "lower.age.limit", # <wpp_age>
  "age", # <wpp_age>
  "female", # <wpp_age>
  "male", # <wpp_age>
  NULL
))
